spring:
  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE_URL}
        instance:
          service-host-type: ip

  cloud:

    config:
      username: ${CLOUD_USERNAME:user}
      password: ${CLOUD_PASSWORD:s3cr3t}

    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true
server:
  port: ${APPLICATION_PORT}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server:
          requests: true