spring:
  cloud:
    config:
      username: ${CLOUD_USERNAME:user}
      password: ${CLOUD_PASSWORD:s3cr3t}

  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE_URL}
        instance:
          service-host-type: ip


server:
  port: ${APPLICATION_PORT:8074}

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://${HOSTNAME:localhost}:${APPLICATION_PORT:8074}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    distribution:
      percentiles-histogram:
        http.server:
          requests: true