package com.tony.department_service.application.event.handlers;


import com.tony.department_service.application.usecases.GetDepartmentByIdOrThrowUseCase;
import com.tony.department_service.domain.entity.DepartmentEntity;
import com.tony.department_service.domain.entity.EmployeeEntity;
import com.tony.department_service.infraestructure.mappers.DepartmentMapper;
import com.tony.department_service.infraestructure.models.Department;
import com.tony.department_service.infraestructure.models.Employee;
import com.tony.department_service.infraestructure.repositories.DepartmentRepository;
import com.tony.department_service.infraestructure.utils.EmployeeTopics;
import com.tony.employee_service.autogenerated.employee.events.EmployeeCreatedEvent;
import lombok.AllArgsConstructor;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.avro.generic.GenericRecord;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Component;


@Component
@Slf4j
@AllArgsConstructor
public class EmployeeCreatedEventHandler {
    private DepartmentRepository repo;
    private GetDepartmentByIdOrThrowUseCase getDepartmentByIdOrThrowUseCase;
    private DepartmentMapper mapper;

    @KafkaListener(topics = "${app.kafka.topics.employee-created}", containerFactory = "kafkaListenerContainerFactory", groupId ="${app.kafka.group-id}" )
    public void handle(EmployeeCreatedEvent event){

        log.info("Receiving the event: {}", event);
        if (event.getDepartmentId() == null){
            return;
        }
        Department department=getDepartmentByIdOrThrowUseCase.execute(event.getDepartmentId());

        DepartmentEntity departmentEntity=mapper.modelToDomainEntity(department);
        EmployeeEntity entity= new EmployeeEntity(event.getId());
        departmentEntity.addNewEmployee(entity);

        Department updatedDepartment=mapper.entityToModel(departmentEntity);
        repo.save(updatedDepartment);
        log.info("Successfully added employee: {}, to department: {}",entity,updatedDepartment);



    }
}
