package com.tony.department_service.application.event.handlers;

import com.tony.department_service.application.usecases.GetDepartmentByIdOrThrowUseCase;
import com.tony.department_service.domain.entity.DepartmentEntity;
import com.tony.department_service.domain.entity.EmployeeEntity;
import com.tony.department_service.infraestructure.mappers.DepartmentMapper;
import com.tony.department_service.infraestructure.models.Department;
import com.tony.department_service.infraestructure.repositories.DepartmentRepository;
import com.tony.department_service.infraestructure.utils.EmployeeTopics;
import com.tony.employee_service.autogenerated.employee.events.EmployeeAssignedToDepartment;
import com.tony.employee_service.autogenerated.employee.events.EmployeeCreatedEvent;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
@Slf4j
public class EmployeeAssignedToDepartmentHandler {

    private final DepartmentRepository repo;
    private final GetDepartmentByIdOrThrowUseCase getDepartmentByIdOrThrowUseCase;
    private final DepartmentMapper mapper;

    @KafkaListener(topics = "${app.kafka.topics.employee-assigned-to-department}", containerFactory = "kafkaListenerContainerFactory", groupId ="${app.kafka.group-id}" )
    public void handle(EmployeeAssignedToDepartment event){

        log.info("Receiving the EmployeeAssignetToDepartmentEvent: {}", event);

        Department department = getDepartmentByIdOrThrowUseCase.execute(event.getDepartmentId());
        DepartmentEntity departmentEntity = mapper.modelToDomainEntity(department);

        departmentEntity.addNewEmployee(new EmployeeEntity(event.getId()));

        Department updatedDepartment = mapper.entityToModel(departmentEntity);

        repo.save(updatedDepartment);
        log.info("Added employee with id = {}, to department with id = {}", event.getId(), department.getId());



    }
}
