
spring:
  application:
    name: registry-service


  config:
    import: optional:file:./registry-service/.env[.properties],optional:file:./.env[.properties],optional:configserver:http://localhost:8075

