package com.tony.employee_service.infraestructure.mapper;

import com.tony.employee_service.autogenerated.employee.events.EmployeeCreatedEvent;
import com.tony.employee_service.autogenerated.employee.events.EmployeeUpdatedEvent;
import com.tony.employee_service.domain.entitys.Employee;
import com.tony.employee_service.infraestructure.dto.UpdateEmployeeDTO;
import com.tony.employee_service.infraestructure.models.EmployeeModel;
import org.mapstruct.*;
import com.tony.employee_service.infraestructure.dto.CreateEmployeeDTO;

@Mapper(componentModel ="spring", unmappedSourcePolicy = ReportingPolicy.IGNORE)
public interface EmployeeMapper extends MapperUtil {


    Employee createEmployeeDtoToEntity(CreateEmployeeDTO dto);


    @Mapping(source ="salary", target = "salary" , ignore = true)
    EmployeeModel entityToModel(Employee entity);

    @Mapping(target = "timestamp", expression = "java(System.currentTimeMillis())")
    EmployeeCreatedEvent modelToEmployeeCreatedEvent(EmployeeModel model);
    Employee modelToEntity(EmployeeModel model);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    EmployeeModel updateDTOToModel(UpdateEmployeeDTO dto, @MappingTarget EmployeeModel model);

    @Mapping(target = "timestamp", expression = "java(System.currentTimeMillis())")
    EmployeeUpdatedEvent modelToUpdatedEmployeeEvent(EmployeeModel model);

}
