package com.tony.employee_service.infraestructure.mapper;

import com.tony.employee_service.autogenerated.employee.events.EmployeeCreatedEvent;
import com.tony.employee_service.autogenerated.employee.events.EmployeeDeletedEvent;
import com.tony.employee_service.autogenerated.employee.events.EmployeeUpdatedEvent;
import com.tony.employee_service.domain.entitys.Employee;
import com.tony.employee_service.domain.event.EmployeeCreatedDomainEvent;
import com.tony.employee_service.domain.event.EmployeeDeletedDomainEvent;
import com.tony.employee_service.domain.event.EmployeeUpdatedDomainEvent;
import com.tony.employee_service.application.dto.UpdateEmployeeDTO;
import com.tony.employee_service.infraestructure.models.EmployeeModel;
import org.mapstruct.*;
import com.tony.employee_service.application.dto.CreateEmployeeDTO;

@Mapper(componentModel ="spring", unmappedSourcePolicy = ReportingPolicy.IGNORE)
public interface EmployeeMapper extends MapperUtil {


    Employee createEmployeeDtoToEntity(CreateEmployeeDTO dto);


    @Mapping(source ="salary", target = "salary" , ignore = true)
    EmployeeModel entityToModel(Employee entity);


    EmployeeCreatedEvent employeeCreatedDomainEventToAvroEvent(EmployeeCreatedDomainEvent event);
    EmployeeDeletedEvent employeeDeletedEventToAvroEvent(EmployeeDeletedDomainEvent event);
    EmployeeUpdatedEvent employeeUpdatedDomainEventToAvroEvent(EmployeeUpdatedDomainEvent event);
    Employee modelToEntity(EmployeeModel model);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    EmployeeModel updateDTOToModel(UpdateEmployeeDTO dto, @MappingTarget EmployeeModel model);


}
