spring:
  application:
    name: employee-service

  config:
    import: optional:file:./employee-service/.env[.properties],optional:file:./.env[.properties],optional:configserver:http://localhost:8075


  profiles:
    active: ${ACTIVE_PROFILE}
