spring:
  application:
    name: employee-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL},optional:file:./employee-service/.env[.properties],optional:file:./.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:employeesdb}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  kafka:
    group-id: employee-service-consumer
    bootstrap-servers: ${BROKER_HOST:localhost}:${BROKER_PORT:9092}
    schema-registry-url: http://${SCHEMA_REGISTRY_HOST:localhost}:${SCHEMA_REGISTRY_PORT:8081}
    topics:
      employee: employee.events
server:
  port: ${APPLICATION_PORT:8080}
