services:
  mongo:
    container_name: company-service-mongo-container
    image: mongo:8.0.21
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "bash -c '</dev/tcp/localhost/27017'" ]
      interval: 10s
      timeout: 20s
      retries: 5
volumes:
  mongodata: