package com.tony.department_service.event.handler;

import com.tony.department_service.application.dto.CreateDepartmentDTO;
import com.tony.department_service.application.usecases.CreateDepartmentUseCase;
import com.tony.department_service.domain.exceptions.DepartmentException;
import com.tony.department_service.helpers.DatabaseHelper;
import com.tony.department_service.infraestructure.event.KafkaProducer;
import com.tony.department_service.infraestructure.models.Department;
import com.tony.department_service.infraestructure.models.Employee;
import com.tony.department_service.infraestructure.repositories.DepartmentRepository;
import com.tony.department_service.infraestructure.utils.EmployeeTopics;
import com.tony.department_service.shared.DatabaseResetManager;
import com.tony.employee_service.autogenerated.employee.events.EmployeeAssignedToDepartment;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.TestExecutionListeners;

import java.time.Instant;
import java.util.List;


@TestExecutionListeners(
        listeners = {DatabaseResetManager.class},
        mergeMode = TestExecutionListeners.MergeMode.MERGE_WITH_DEFAULTS
)
@SpringBootTest
public class TestAssignedEmployeeToDepartmentEventHandler {
    @Autowired
    private DepartmentRepository repo;
    @Autowired
    private EmployeeTopics topics;

    @Autowired
    private DatabaseHelper helper;
    @Autowired
    private CreateDepartmentUseCase createDepartmentUseCase;

    @Autowired
    private KafkaProducer producer;

    public Department getDepartmentForTest(){
        CreateDepartmentDTO dto= CreateDepartmentDTO.builder()
                .name("Machine Learning")
                .leadId("356")
                .description("The department of DevOps")
                .build();

        return createDepartmentUseCase.execute(dto);
    }

    @Test
    void shouldHandleEventSuccessfully(){
        Department department = getDepartmentForTest();
        EmployeeAssignedToDepartment event = EmployeeAssignedToDepartment.newBuilder()
                .setId("12345")
                .setDepartmentId(department.getId())
                .setTimestamp(Instant.now().toEpochMilli())
                .build();

        producer.send(topics.getEmployeeAssignedToDepartment(),event);

        Department updatedDepartment = helper.findByIdAndPredicate(department.getId(),d -> d.getEmployees() != null && d.getEmployees().size() == 1);

        Employee employee = updatedDepartment.getEmployees().getFirst();
        Assertions.assertEquals("12345", employee.getId());
    }


}
