package com.tony.department_service.event.handler;

import com.tony.department_service.application.dto.CreateDepartmentDTO;
import com.tony.department_service.application.usecases.CreateDepartmentUseCase;
import com.tony.department_service.helpers.DatabaseHelper;
import com.tony.department_service.infraestructure.config.KafkaProducerConfig;
import com.tony.department_service.infraestructure.config.KafkaProperties;
import com.tony.department_service.infraestructure.event.KafkaProducer;
import com.tony.department_service.infraestructure.models.Department;
import com.tony.department_service.infraestructure.repositories.DepartmentRepository;
import com.tony.department_service.infraestructure.utils.EmployeeTopics;
import com.tony.department_service.shared.DatabaseResetManager;
import com.tony.employee_service.autogenerated.employee.events.EmployeeCreatedEvent;
import org.apache.avro.generic.GenericRecord;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.test.context.TestExecutionListeners;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Objects;

@TestExecutionListeners(
        listeners = {DatabaseResetManager.class},
        mergeMode = TestExecutionListeners.MergeMode.MERGE_WITH_DEFAULTS
)
@SpringBootTest
public class TestEmployeeCreatedHandler {

    @Autowired
    private EmployeeTopics topics;

    @Autowired
    private DatabaseHelper helper;
    @Autowired
    private CreateDepartmentUseCase createDepartmentUseCase;

    @Autowired
    private KafkaProducer producer;

    public Department getDepartmentForTest(){
        CreateDepartmentDTO dto= CreateDepartmentDTO.builder()
                .name("Machine Learning")
                .leadId("356")
                .description("The department of DevOps")
                .build();

        return createDepartmentUseCase.execute(dto);
    }

    @Test
    void shouldHandleEmployeeCreatedEventSuccessfully(){
        Department department= getDepartmentForTest();
        EmployeeCreatedEvent event= EmployeeCreatedEvent.newBuilder()
                .setFullName("Juan Carlos")
                .setEmail("carlos@gmail.com")
                .setPosition("SOFTWARE_ENGINEER")
                .setRole("JUNIOR")
                .setSalary(BigDecimal.valueOf(400L))
                .setId("542")
                .setDepartmentId(department.getId())
                .setTimestamp(Instant.now().toEpochMilli())
                .build();
        producer.send(topics.getEmployeeCreated(),event);
        Department updatedDepartment=helper.findByIdAndPredicate(department.getId(), d -> d.getEmployees() != null && d.getEmployees().size() == 1);

        Assertions.assertEquals(1,updatedDepartment.getEmployees().size());
        Assertions.assertEquals("Juan Carlos", updatedDepartment.getEmployees().getFirst().getName());



    }
}
