package com.tony.employee_service.infraestructure.event.specificproducer;

import com.tony.employee_service.autogenerated.employee.events.EmployeeCreatedEvent;
import com.tony.employee_service.autogenerated.employee.events.EmployeeDeletedEvent;
import com.tony.employee_service.autogenerated.employee.events.EmployeeUpdatedEvent;
import com.tony.employee_service.domain.event.EmployeeCreatedDomainEvent;
import com.tony.employee_service.domain.event.EmployeeDeletedDomainEvent;
import com.tony.employee_service.domain.event.EmployeeUpdatedDomainEvent;
import com.tony.employee_service.infraestructure.event.producer.KafkaProducer;
import com.tony.employee_service.infraestructure.mapper.EmployeeMapper;
import com.tony.employee_service.infraestructure.utils.KafkaTopics;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

@Service
@Slf4j
@RequiredArgsConstructor
public class EmployeeEventsProducer {
  private final KafkaProducer producer;
  private final KafkaTopics topics;
  private final EmployeeMapper mapper;

  public void produceEmployeeCreatedEvent(EmployeeCreatedDomainEvent domainEvent) {
    log.info(
        "Sending employee created event to topic: {}, Event: {}",
        topics.getEmployeeCreated(),
        domainEvent);
    EmployeeCreatedEvent event = mapper.employeeCreatedDomainEventToAvroEvent(domainEvent);
    producer.send(topics.getEmployeeCreated(), event);
  }

  public void produceEmployeeUpdatedEvent(EmployeeUpdatedDomainEvent domainEvent) {
    log.info(
        "Sending employee updated event to topic: {}, Event: {}",
        topics.getEmployeeUpdated(),
        domainEvent);
    EmployeeUpdatedEvent avroEvent = mapper.employeeUpdatedDomainEventToAvroEvent(domainEvent);
    producer.send(topics.getEmployeeUpdated(), avroEvent);
  }

  public void produceEmployeeDeletedEvent(EmployeeDeletedDomainEvent domainEvent) {
    log.info(
        "Sending employee deleted event to topic: {}, Event: {}",
        topics.getEmployeeDeleted(),
        domainEvent);
    EmployeeDeletedEvent event = mapper.employeeDeletedEventToAvroEvent(domainEvent);
    producer.send(topics.getEmployeeDeleted(), event);
  }
}
