package com.tony.employee_service.infraestructure.event.specificproducer;

import com.tony.employee_service.autogenerated.employee.events.EmployeeCreatedEvent;
import com.tony.employee_service.autogenerated.employee.events.EmployeeDeletedEvent;
import com.tony.employee_service.infraestructure.event.producer.KafkaProducer;
import com.tony.employee_service.infraestructure.mapper.EmployeeMapper;
import com.tony.employee_service.infraestructure.models.EmployeeModel;
import com.tony.employee_service.infraestructure.utils.KafkaTopics;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.Instant;

@Service
@Slf4j
@RequiredArgsConstructor
public class EmployeeEventsProducer {
    private final KafkaProducer producer;
    private final KafkaTopics topics;
    private final EmployeeMapper mapper;

    public void produceEmployeeCreatedEvent(EmployeeModel model){
        log.info("Sending employee created event to topic: {}, Event: {}", topics.getEmployee(), model);
        EmployeeCreatedEvent event= mapper.modelToEmployeeCreatedEvent(model);
        producer.send(topics.getEmployee(),event);

    }

    public void produceEmployeeUpdatedEvent(EmployeeModel model){
        log.info("Sending employee updated event to topic: {}, Event: {}", topics.getEmployee(), model);
        EmployeeCreatedEvent event= mapper.modelToEmployeeCreatedEvent(model);
        producer.send(topics.getEmployee(),event);

    }

    public void produceEmployeeDeletedEvent(EmployeeModel model){
        log.info("Sending employee deleted event to topic: {}, Event: {}", topics.getEmployee(), model);
        EmployeeDeletedEvent event= EmployeeDeletedEvent.newBuilder().setId(model.getId()).setTimestamp(System.currentTimeMillis()).build();
        producer.send(topics.getEmployee(), event);

    }
}
